env:
  node: true
  es6: true
  es2021: true
  es2024: true
extends: eslint:recommended
parser: '@babel/eslint-parser'
parserOptions:
  babelOptions:
    configFile: false
    plugins: [ "@babel/plugin-syntax-import-attributes" ]
  requireConfigFile: false
  ecmaVersion: latest
  sourceType: module
rules: {}
