#!/bin/bash
set -e

ENV_FILE="$(cd "$(dirname "$0")" && pwd)/.env"

if [ -f "$ENV_FILE" ]; then
    echo ".env already exists, not overwriting." >&2
    exit 0
fi

DB_ROOT_PW=$(openssl rand -base64 24)
NT_DB_PW=$(openssl rand -base64 24)

cat > "$ENV_FILE" <<EOF
# NicTool API environment configuration
# Generated by docker/generate-env.sh

# --- Database (MariaDB/MySQL) ---
DB_ROOT_PASSWORD=$DB_ROOT_PW
NICTOOL_DB_NAME=nictool
NICTOOL_DB_USER=nictool
NICTOOL_DB_USER_PASSWORD=$NT_DB_PW

# --- API config overrides (optional, override conf.d/*.toml defaults) ---
# NICTOOL_DB_HOST=127.0.0.1
# NICTOOL_DB_PORT=3306
# NICTOOL_HTTP_HOST=localhost
# NICTOOL_HTTP_PORT=3000

# --- Docker Compose port mapping ---
# DB_PORT=3307
# API_PORT=3000
EOF

echo "Generated $ENV_FILE with random passwords."
