name: CI

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:

env:
  CI: true
  NODE_ENV: test
  NODE_VER: 22

jobs:
  lint:
    uses: NicTool/.github/.github/workflows/lint.yml@main

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VER }}
      - uses: actions/checkout@v4
      - run: npm install
      - name: Initialize MySQL
        run: sh sql/init-mysql.sh
      - name: run coverage
        run: npx -y c8 --reporter=lcov npm test
        env:
          NODE_ENV: cov
      - name: codecov
        uses: codecov/codecov-action@v2
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}

  get-lts:
    runs-on: ubuntu-latest
    steps:
      - id: get
        uses: msimerson/node-lts-versions@v1
    outputs:
      active: ${{ steps.get.outputs.active }}
      maintenance: ${{ steps.get.outputs.maintenance }}
      lts: ${{ steps.get.outputs.lts }}
      current: ${{ steps.get.outputs.current }}
      min: ${{ steps.get.outputs.min }}

  test:
    needs: [ get-lts ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ${{ fromJson(needs.get-lts.outputs.active) }}
      fail-fast: false
    steps:
      - run: sudo /etc/init.d/mysql start
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: sh sql/init-mysql.sh
      - run: npm install
      - run: npm test

  test-mac:
    needs: [ get-lts ]
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.get-lts.outputs.active) }}
      fail-fast: false
    steps:
      - name: Install & Start MySQL
        run: |
          brew install mysql@8.4
          brew services start mysql@8.4
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
        with:
          node-version: ${{ matrix.node-version }}
      - run: sh sql/init-mysql.sh
      - run: npm install
      - run: npm test

  test-win:
    # if: false
    needs: [ get-lts ]
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.get-lts.outputs.active) }}
        experimental: [true]
      fail-fast: false
    steps:
      - name: Install MySQL
        run: |
          choco install mysql
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: Node ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - run: sh sql/init-mysql.sh
      - run: npm install
      - run: sh test.sh
