name: publish

on:
  release:
    types: [published]

env:
  CI: true
  node-version: 22

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: sudo /etc/init.d/mysql start
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node-version }}
      - run: sh sql/init-mysql.sh
      - run: npm install
      - run: npm test

  publish-npm:
    permissions:
      contents: read
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        name: Node ${{ env.node-version }}
        with:
          node-version: ${{ env.node-version }}
          registry-url: https://registry.npmjs.org/

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          # fetch-depth 0 needed by GitHub Release

      - name: publish to NPM
        run: |
          VERSION=$(node -e 'console.log(require("./package.json").version)')
          if printf '%s' "$VERSION" | grep -q -- '-'; then
            # prerelease versions get the "next" tag
            npm publish --access public --tag next
          else
            npm publish --access public
          fi

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@nictool'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}